import "server-only";
import ExcelJS, { type Cell, type Fill, type Font, type Worksheet } from "exceljs";
import type { ArtifactManifest, ReportDataModel } from "../artifacts/types";
import { parseMarkdown, type DocumentBlock } from "./content";
import { createOffPageSeoXlsx } from "./off-page-xlsx";
import { matchWorkbookSheet, uniqueTableHeaders, workbookRowHeight, workbookSheetLabel, workbookCellValue } from "./workbook-layout";

const PURPLE = "8B2CE0";
const VIOLET = "7030B5";
const PINK = "E8447A";
const INK = "1A1A1A";
const SLATE = "5B5B63";
const PAPER = "FFFDFB";
const BLUSH = "F7DFEA";
const LILAC = "EADCF5";
const BLUE = "D8EEF8";
const LINE = "EADBD5";

type WorkbookModule = { type: string; title: string; markdown: string };
type SpreadsheetArgs = {
  companyName: string;
  companyWebsite?: string;
  companyCategory?: string | null;
  title: string;
  documentType?: string;
  markdown: string;
  updatedAt: Date;
  sourceCount: number;
  modules?: WorkbookModule[];
  reportModel?: ReportDataModel;
  manifest?: ArtifactManifest;
};

const titleFill: Fill = { type: "pattern", pattern: "solid", fgColor: { argb: PURPLE } };
const titleFont: Partial<Font> = { name: "Arial", color: { argb: "FFFFFF" }, bold: true };

function sheetSafe(value: string): string {
  return value.replace(/[\\/*?:\[\]]/g, " ").replace(/\s+/g, " ").trim().slice(0, 31) || "Sheet";
}

function uniqueSheetName(workbook: ExcelJS.Workbook, requested: string): string {
  const base = sheetSafe(requested);
  if (!workbook.getWorksheet(base)) return base;
  for (let index = 2; index < 100; index += 1) {
    const suffix = ` ${index}`;
    const candidate = `${base.slice(0, 31 - suffix.length)}${suffix}`;
    if (!workbook.getWorksheet(candidate)) return candidate;
  }
  return `${base.slice(0, 26)} ${Date.now().toString().slice(-4)}`;
}

function tableSafe(value: string): string {
  const safe = value.replace(/[^a-z0-9_]/gi, "_").replace(/^[^a-z_]+/i, "T_").slice(0, 220);
  return safe || `Table_${Date.now()}`;
}

function setBaseSheet(sheet: Worksheet) {
  sheet.properties.defaultRowHeight = 19;
  sheet.views = [{ state: "frozen", ySplit: 5, showGridLines: false }];
  sheet.pageSetup = { orientation: "landscape", paperSize: 9, fitToPage: true, fitToWidth: 1, fitToHeight: 0, printTitlesRow: "1:5", margins: { left: 0.25, right: 0.25, top: 0.45, bottom: 0.45, header: 0.2, footer: 0.2 } };
  sheet.headerFooter.oddHeader = `&L&8KREV AI / AI CMO&R&8${sheet.name}`;
  sheet.headerFooter.oddFooter = "&L&8Evidence-led AI CMO workbook&R&8Page &P of &N";
}

function applyCellBase(cell: Cell) {
  cell.font = { name: "Arial", size: 10, color: { argb: SLATE } };
  cell.alignment = { vertical: "top", wrapText: true };
  cell.border = { bottom: { style: "hair", color: { argb: LINE } } };
}

function setColumnWidths(sheet: Worksheet, widths: number[]) {
  widths.forEach((width, index) => { sheet.getColumn(index + 1).width = Math.min(52, Math.max(12, width)); });
}

function styleDataTable(sheet: Worksheet, headerRow: number, columnCount: number, dataRowCount: number) {
  for (let column = 1; column <= columnCount; column += 1) {
    const header = sheet.getCell(headerRow, column);
    header.fill = titleFill;
    header.font = { ...titleFont, size: 9 };
    header.alignment = { vertical: "middle", wrapText: true };
  }
  sheet.getRow(headerRow).height = 24;
  for (let index = 0; index < dataRowCount; index += 1) {
    const row = sheet.getRow(headerRow + index + 1);
    row.eachCell({ includeEmpty: true }, (cell, column) => {
      if (column > columnCount) return;
      applyCellBase(cell);
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: index % 2 ? PAPER : BLUE } };
    });
  }
}

function addSheetHeader(sheet: Worksheet, args: { title: string; subtitle: string; companyName: string }) {
  sheet.mergeCells("A1:H1");
  const title = sheet.getCell("A1");
  title.value = args.title;
  title.font = { name: "Arial", size: 18, bold: true, color: { argb: INK } };
  title.alignment = { vertical: "middle" };
  sheet.getRow(1).height = 28;
  sheet.mergeCells("A2:H2");
  const subtitle = sheet.getCell("A2");
  subtitle.value = args.subtitle;
  subtitle.font = { name: "Arial", size: 9, italic: true, color: { argb: SLATE } };
  subtitle.fill = { type: "pattern", pattern: "solid", fgColor: { argb: BLUSH } };
  subtitle.alignment = { vertical: "middle", wrapText: true };
  sheet.getRow(2).height = 25;
  sheet.mergeCells("A3:H3");
  const meta = sheet.getCell("A3");
  meta.value = `${args.companyName}  |  Generated by KREV AI`;
  meta.font = { name: "Arial", size: 8, bold: true, color: { argb: VIOLET } };
  meta.alignment = { vertical: "middle" };
}

function firstNarrative(blocks: DocumentBlock[]): string {
  const block = blocks.find((item) => item.type === "paragraph" || item.type === "quote" || item.type === "bullet");
  return block && "text" in block ? block.text.slice(0, 420) : "See the structured module sheet for the evidence, decisions, and actions.";
}

function sourceUrls(markdown: string): string[] {
  return Array.from(markdown.matchAll(/https?:\/\/[^\s)\]>]+/g), (match) => match[0].replace(/[.,;:]$/, ""))
    .filter((url, index, values) => values.indexOf(url) === index);
}

function addOverview(workbook: ExcelJS.Workbook, args: SpreadsheetArgs, modules: WorkbookModule[]) {
  const name = args.manifest?.requiredSheets.find((name) => /summary/i.test(name)) ?? "Overview";
  const sheet = workbook.getWorksheet(name) ?? workbook.addWorksheet(name, { properties: { tabColor: { argb: PURPLE } } });
  setBaseSheet(sheet);
  addSheetHeader(sheet, { title: args.title, subtitle: "Review the findings, open the working tables, then assign and track actions. Blank inputs are not measured zeros.", companyName: args.companyName });
  setColumnWidths(sheet, [22, 28, 62, 16, 16, 16, 16, 16]);

  const facts = [
    ["UPDATED", args.updatedAt],
    ["MODULES", modules.length],
    ["SOURCES", new Set(modules.flatMap((module) => sourceUrls(module.markdown))).size],
    ["FORMAT", "XLSX · editable and filterable"],
  ] as Array<[string, string | number | Date]>;
  facts.forEach(([label, value], index) => {
    const column = 1 + index * 2;
    const labelCell = sheet.getCell(5, column);
    const valueCell = sheet.getCell(6, column);
    sheet.mergeCells(5, column, 5, column + 1);
    sheet.mergeCells(6, column, 6, column + 1);
    labelCell.value = label;
    labelCell.fill = titleFill;
    labelCell.font = { ...titleFont, size: 8 };
    labelCell.alignment = { vertical: "middle", horizontal: "center" };
    valueCell.value = value;
    valueCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: index % 2 ? LILAC : BLUE } };
    valueCell.font = { name: "Arial", size: 12, bold: true, color: { argb: INK } };
    valueCell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    if (value instanceof Date) valueCell.numFmt = "mmm d, yyyy";
    sheet.getRow(6).height = 34;
  });

  const rows = modules.map((module, index) => {
    const blocks = parseMarkdown(module.markdown);
    return [index + 1, module.title, firstNarrative(blocks), blocks.filter((block) => block.type === "table").length, sourceUrls(module.markdown).length];
  });
  sheet.addTable({
    name: "Workbook_Module_Map",
    ref: "A9",
    headerRow: true,
    totalsRow: false,
    style: { theme: "TableStyleMedium4", showRowStripes: true },
    columns: ["#", "Module", "Executive takeaway", "Structured tables", "Source links"].map((name) => ({ name })),
    rows,
  });
  styleDataTable(sheet, 9, 5, rows.length);
  sheet.getColumn(1).width = 7;
  sheet.getColumn(2).width = 28;
  sheet.getColumn(3).width = 72;
  sheet.getColumn(4).width = 18;
  sheet.getColumn(5).width = 15;
  sheet.getRows(10, Math.max(1, rows.length))?.forEach((row) => { row.height = 44; row.eachCell(applyCellBase); });
}

function addNarrativeSheet(workbook: ExcelJS.Workbook, args: SpreadsheetArgs, module: WorkbookModule, moduleIndex: number) {
  const blocks = parseMarkdown(module.markdown);
  const sheet = workbook.addWorksheet(uniqueSheetName(workbook, modulesNoteName(moduleIndex)), { properties: { tabColor: { argb: moduleIndex % 2 ? PINK : VIOLET } } });
  setBaseSheet(sheet);
  addSheetHeader(sheet, { title: module.title, subtitle: "Evidence → interpretation → decision → confidence → validation → measurement", companyName: args.companyName });
  setColumnWidths(sheet, [7, 30, 72, 24, 18, 18, 18, 18]);
  let row = 5;
  let section = "Executive synthesis";
  let tableIndex = 0;

  for (const block of blocks) {
    if (block.type === "h1") continue;
    if (block.type === "h2" || block.type === "h3") {
      section = block.text;
      sheet.mergeCells(row, 1, row, 8);
      const cell = sheet.getCell(row, 1);
      cell.value = block.text;
      cell.fill = block.type === "h2" ? titleFill : { type: "pattern", pattern: "solid", fgColor: { argb: LILAC } };
      cell.font = { name: "Arial", bold: true, size: block.type === "h2" ? 11 : 10, color: { argb: block.type === "h2" ? "FFFFFF" : VIOLET } };
      cell.alignment = { vertical: "middle", wrapText: true };
      sheet.getRow(row).height = 24;
      row += 1;
      continue;
    }
    if (block.type === "table") {
      tableIndex += 1;
      const matched = matchWorkbookSheet(section, args.manifest?.requiredSheets ?? [], workbook.worksheets.filter((item) => item.rowCount > 0).map((item) => item.name));
      const tableSheet = (matched ? workbook.getWorksheet(matched) : undefined) ?? workbook.addWorksheet(uniqueSheetName(workbook, matched ?? section), { properties: { tabColor: { argb: BLUE } } });
      setBaseSheet(tableSheet);
      addSheetHeader(tableSheet, { title: section, subtitle: `${module.title} · structured, filterable export`, companyName: args.companyName });
      const headers = uniqueTableHeaders(block.rows[0]);
      const dataRows = block.rows.slice(1).map((values) => headers.map((_, index) => values[index] ?? ""));
      tableSheet.addTable({ name: tableSafe(`Module_${moduleIndex + 1}_Table_${tableIndex}`), ref: "A5", headerRow: true, totalsRow: false, style: { theme: "TableStyleLight1", showRowStripes: false }, columns: headers.map((name) => ({ name })), rows: dataRows });
      styleDataTable(tableSheet, 5, headers.length, dataRows.length);
      headers.forEach((_, index) => {
        const longest = Math.max(headers[index].length, ...dataRows.slice(0, 60).map((values) => String(values[index] ?? "").length));
        tableSheet.getColumn(index + 1).width = Math.min(52, Math.max(13, Math.ceil(longest * 0.78)));
      });
      tableSheet.getRows(6, Math.max(1, dataRows.length))?.forEach((tableRow) => { tableRow.eachCell(applyCellBase); });
      dataRows.forEach((values, index) => values.forEach((value, column) => {
        const cell = tableSheet.getCell(index + 6, column + 1);
        const typed = workbookCellValue(value, headers[column]);
        cell.value = typed.value;
        if (typed.numFmt) cell.numFmt = typed.numFmt;
      }));
      sheet.mergeCells(row, 1, row, 8);
      const reference = sheet.getCell(row, 1);
      reference.value = { text: `Open structured table: ${tableSheet.name}`, hyperlink: `#'${tableSheet.name.replace(/'/g, "''")}'!A1` };
      reference.font = { name: "Arial", size: 9, bold: true, color: { argb: PURPLE }, underline: true };
      reference.fill = { type: "pattern", pattern: "solid", fgColor: { argb: BLUE } };
      reference.alignment = { vertical: "middle" };
      row += 2;
      continue;
    }
    const marker = block.type === "bullet" ? "BULLET" : block.type === "number" ? "STEP" : block.type === "quote" ? "NOTE" : "";
    if (marker) {
      sheet.getCell(row, 1).value = marker;
      sheet.getCell(row, 1).font = { name: "Arial", size: 8, bold: true, color: { argb: PURPLE } };
      sheet.getCell(row, 1).alignment = { vertical: "top", horizontal: "center", wrapText: true };
    }
    sheet.mergeCells(row, 2, row, 8);
    const cell = sheet.getCell(row, 2);
    cell.value = block.text;
    cell.font = { name: "Arial", size: 10, color: { argb: block.type === "quote" ? INK : SLATE }, italic: block.type === "quote" };
    cell.alignment = { vertical: "top", wrapText: true };
    if (block.type === "quote") cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: BLUSH } };
    sheet.getRow(row).height = Math.min(409, Math.max(28, 18 + Math.ceil(block.text.length / 115) * 15));
    row += 1;
  }
  sheet.pageSetup.printTitlesRow = "1:3";
}

function modulesNoteName(index: number) { return index ? `Research Notes ${index + 1}` : "Research Notes"; }

function addSources(workbook: ExcelJS.Workbook, args: SpreadsheetArgs, modules: WorkbookModule[]) {
  const name = args.manifest?.requiredSheets.find((name) => /source_register/i.test(name)) ?? "Source Register";
  const sheet = workbook.getWorksheet(name) ?? workbook.addWorksheet(name, { properties: { tabColor: { argb: PINK } } });
  setBaseSheet(sheet);
  addSheetHeader(sheet, { title: "Source Register", subtitle: "URLs preserved from the generated document evidence. Verify freshness before execution.", companyName: args.companyName });
  setColumnWidths(sheet, [8, 28, 72, 18, 18, 18, 18, 18]);
  const rows = modules.flatMap((module) => sourceUrls(module.markdown).map((url) => [module.title, url, "Generated evidence pack"]));
  const uniqueRows = rows.filter((row, index, values) => values.findIndex((candidate) => candidate[1] === row[1]) === index);
  sheet.addTable({ name: "Workbook_Source_Register", ref: "A5", headerRow: true, totalsRow: false, style: { theme: "TableStyleMedium4", showRowStripes: true }, columns: ["Module", "Source URL", "Use"].map((name) => ({ name })), rows: uniqueRows.length ? uniqueRows : [["Workbook", "No source URL embedded", "Connect or regenerate with source evidence"]] });
  styleDataTable(sheet, 5, 3, Math.max(1, uniqueRows.length));
  sheet.getColumn(1).width = 28;
  sheet.getColumn(2).width = 82;
  sheet.getColumn(3).width = 34;
  sheet.getRows(6, Math.max(1, uniqueRows.length))?.forEach((row) => { row.height = 30; row.eachCell(applyCellBase); });
  uniqueRows.forEach((row, index) => {
    const cell = sheet.getCell(6 + index, 2);
    cell.value = { text: row[1], hyperlink: row[1] };
    cell.font = { name: "Arial", size: 10, color: { argb: PURPLE }, underline: true };
  });
}

function addActionTracker(workbook: ExcelJS.Workbook, args: SpreadsheetArgs, model: ReportDataModel) {
  const name = args.manifest?.requiredSheets.find((name) => /action_tracker|priority_backlog/i.test(name)) ?? "Action Tracker";
  const sheet = workbook.getWorksheet(name) ?? workbook.addWorksheet(name, { properties: { tabColor: { argb: PINK } } });
  setBaseSheet(sheet);
  sheet.views = [{ state: "frozen", ySplit: 5, xSplit: 2, showGridLines: false }];
  addSheetHeader(sheet, { title: "Action Tracker", subtitle: "Update owners, status and dates. Evidence links appear only where the recommendation cites a source.", companyName: args.companyName });
  const recommendations = model.recommendations.length ? model.recommendations : [{ id: "VALIDATE-001", priority: "unrated" as const, title: "Validate the action plan", detail: "Add structured recommendations to the source report before assigning work.", findingIds: [] }];
  const rows = recommendations.map((item, index) => {
    const row = index + 6;
    const owner = item.detail.match(/(?:^|;\s*)Owner:\s*([^;]+)/i)?.[1]?.trim() || null;
    const dueDate = item.detail.match(/(?:due date|due):\s*(\d{4}-\d{2}-\d{2})/i)?.[1];
    const suppliedStatus = item.detail.match(/(?:^|;\s*)Status:\s*([^;]+)/i)?.[1]?.trim();
    const status = ["Not started", "In progress", "Blocked", "Complete"].find((value) => value.toLowerCase() === suppliedStatus?.toLowerCase()) ?? "Not started";
    const evidenceUrls = model.lineage.filter((link) => link.recommendationId === item.id)
      .map((link) => model.sources.find((source) => source.id === link.sourceId)?.url).filter(Boolean).join("\n") || null;
    return [item.id, item.priority.toUpperCase(), item.detail, owner, status,
      dueDate ? workbookCellValue(dueDate, "Due date").value : null,
      item.findingIds.join(", ") || null, evidenceUrls,
      { formula: `IF(B${row}="HIGH",3,IF(B${row}="MEDIUM",2,IF(B${row}="LOW",1,"")))`, result: ({ high: 3, medium: 2, low: 1, unrated: "" } as const)[item.priority] },
      { formula: `IF(E${row}="Complete",1,IF(E${row}="Not started",0,""))`, result: status === "Complete" ? 1 : status === "Not started" ? 0 : "" },
    ];
  });
  const columns = ["Recommendation ID", "Priority", "Recommendation", "Owner", "Status", "Due Date", "Finding IDs", "Evidence URLs", "Priority Score", "Progress"];
  sheet.addTable({ name: "Workbook_Action_Tracker", ref: "A5", headerRow: true, totalsRow: false, style: { theme: "TableStyleMedium4", showRowStripes: true }, columns: columns.map((name) => ({ name })), rows });
  styleDataTable(sheet, 5, columns.length, rows.length);
  setColumnWidths(sheet, [20, 13, 62, 20, 18, 16, 20, 14, 16, 14]);
  sheet.getRows(6, rows.length)?.forEach((row) => { row.height = 42; row.eachCell(applyCellBase); });
  for (let row = 6; row < 6 + rows.length; row += 1) {
    for (const column of [4, 5, 6]) {
      sheet.getCell(row, column).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "F3F5FF" } };
      sheet.getCell(row, column).font = { name: "Arial", size: 10, color: { argb: "2453A6" } };
    }
    sheet.getCell(row, 5).dataValidation = { type: "list", allowBlank: false, formulae: ['"Not started,In progress,Blocked,Complete"'] };
    sheet.getCell(row, 6).numFmt = "yyyy-mm-dd";
    sheet.getCell(row, 9).numFmt = "0";
    sheet.getCell(row, 10).numFmt = "0%";
  }
  sheet.addConditionalFormatting({ ref: `B6:B${5 + rows.length}`, rules: [
    { type: "containsText", priority: 1, operator: "containsText", text: "HIGH", style: { font: { color: { argb: "FFFFFF" }, bold: true }, fill: { type: "pattern", pattern: "solid", bgColor: { argb: "C8425B" }, fgColor: { argb: "C8425B" } } } },
    { type: "containsText", priority: 2, operator: "containsText", text: "MEDIUM", style: { font: { color: { argb: "FFFFFF" }, bold: true }, fill: { type: "pattern", pattern: "solid", bgColor: { argb: "D88918" }, fgColor: { argb: "D88918" } } } },
  ] });
}

export async function createBrandedXlsx(args: SpreadsheetArgs): Promise<Buffer> {
  if (args.documentType === "BACKLINK_OUTREACH_BLUEPRINT") {
    return createOffPageSeoXlsx(args);
  }
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "KREV AI";
  workbook.company = "KREV AI";
  workbook.title = `${args.companyName} - ${args.title}`;
  workbook.subject = "Evidence-led AI CMO workbook";
  workbook.description = "A structured, editable spreadsheet export generated by KREV AI.";
  workbook.created = args.updatedAt;
  workbook.modified = args.updatedAt;
  workbook.calcProperties.fullCalcOnLoad = true;
  for (const name of args.manifest?.requiredSheets ?? []) workbook.addWorksheet(name);

  const modules = args.modules?.length ? args.modules : [{ type: "DOCUMENT", title: args.title, markdown: args.markdown }];
  addOverview(workbook, args, modules);
  if (args.reportModel) addActionTracker(workbook, args, args.reportModel);
  modules.forEach((module, index) => addNarrativeSheet(workbook, args, module, index));
  addSources(workbook, args, modules);

  for (const required of args.manifest?.requiredSheets ?? []) {
    const sheet = workbook.getWorksheet(required)!;
    if (sheet.rowCount) continue;
    setBaseSheet(sheet);
    addSheetHeader(sheet, { title: workbookSheetLabel(required), subtitle: "No matching structured records were supplied in this report. Add verified records or regenerate with the missing evidence.", companyName: args.companyName });
    sheet.getCell("A5").value = "Data unavailable";
    sheet.getCell("A5").font = { name: "Arial", bold: true, color: { argb: SLATE } };
    sheet.getColumn(1).width = 40;
  }

  workbook.eachSheet((sheet) => {
    sheet.eachRow((row) => row.eachCell((cell) => {
      if (!cell.font) cell.font = { name: "Arial", size: 10, color: { argb: SLATE } };
    }));
    sheet.getCell("A1").note = "Generated from KREV AI document evidence. Source URLs and confidence boundaries should be reviewed before execution.";
    sheet.eachRow((row, index) => {
      if (index < 5 || row.getCell(1).isMerged || row.getCell(2).isMerged) return;
      const values: string[] = [];
      const widths: number[] = [];
      row.eachCell({ includeEmpty: true }, (cell, column) => { values[column - 1] = cell.text; widths[column - 1] = sheet.getColumn(column).width ?? 30; });
      row.height = workbookRowHeight(values, widths);
    });
    sheet.pageSetup.printArea = `A1:${sheet.getRow(5).cellCount > 0 ? sheet.getColumn(Math.max(8, sheet.columnCount)).letter : "H"}${sheet.rowCount}`;
  });
  const output = await workbook.xlsx.writeBuffer();
  return Buffer.from(output);
}
